[FEAT] 메인페이지 페이지네이션 추가
Kernel360/F2-omocha-FE pull request #125
Opened 2024-11-20 08:35 UTC by kimeodml

- Close #120 

## What is this PR? 🔍

- 기능 : 페이지네이션 추가
- issue : #120 

## Changes 📝
- params 값을 일치시켜도 새로고침하면 이미지가 두 번 요청 처리가 돼서 우선 CommonImage 컴포넌트만 만들어 놓았고 적용은 안했습니다.
- 경매 리스트 페이지네이션 적용하였고, 찜은 무한 스크롤로 구현했습니다.

## ScreenShot 📷
<img width="657" alt="image" src="https://github.com/user-attachments/assets/250f2b33-39ca-4113-b014-3d22f181ed33">

## Precaution

## ✔️ Please check if the PR fulfills these requirements

- [ ] It's submitted to the correct branch, not the `develop` branch unconditionally?
- [ ] If on a hotfix branch, ensure it targets `main`?
- [ ] There are no warning message when you run `npm run lint`

2024-11-20 10:41 UTC, haejinyun requested changes
페이지네이션에서 currentPage 값을 api에서 넘어온 값을 써서 Url값이랑 달라 1을 계속 더하고 빼는 로직이 들어있는데 이게 생각보다 생각을 더 복잡하게 할 것 같아요. 
그냥 url에 달려있는 값으로만 사용을 하고 api에 있는 값을 안보는 것은 어떤가요?

1부터 시작하는 값으로 로직에서는 사용하고 api를 보내는 곳에서만 -1해서 보내주는 것이지요.
이후 api가 1부터 시작하는 것으로 수정된다면 api를 보내는 곳에서 -1만 제외하면 되는 것이라 수정도 용이할 것같아요.

추가적으로 이건 제가 선호하는 방식인데 상수를 사용할때는 간단한 것이라도 상수화 해서 명확한 네이밍이 있는 변수를 활용하는 것이 유지보수나 이슈 해결에 용이할 것 같아요. 

첫 페이지를 1이라고 쓰는 것보다 `const FIRST_PAGE = 1`이런식으로 두면 나중에 시작페이지가 0으로 바뀌어도 빠르게 수정 가능하다고 생각합니다!!

2024-11-20 10:41 UTC, haejinyun commented on src/components/Pagination/index.tsx
> +    return currentPage + 1 === page ? S.base.currentNumbers : S.base.numbers;
```suggestion
    return currentPage === page ? S.base.currentNumbers : S.base.numbers;
```
`currentPage`이 값을 url에서 가져온 값을 사용한다면 +1이 필요없지 않을까요?

2024-11-20 10:41 UTC, haejinyun commented on src/components/Pagination/index.tsx
> +  };
이렇게 반복되는 로직은 그냥 조건문만 다른거니 같을 요소 즉 1인지 totalPage인지만 인자로 받고 인자로 받은 요소와 같다면 S.base.numbers반환 아니면 S.base.currentNumbers반환하면 좋을 것 같아요

```typescript
const chevronRightStyle = (compareValue) => {
  if(compareValue === currentPage){
    return S.base.numbers
  }
  else {
    return S.base.currentNumbers;
  }
 }
```
이런 느낌..? 하나로 합칠 수 있지 않을까? 싶어용

2024-11-20 10:41 UTC, haejinyun commented on src/components/Pagination/index.tsx
> +          disabled={currentPage + 1 === 1}
```suggestion
const LASTPAGE = 1
----
          disabled={currentPage + 1 === LASTPAGE}
```
어디서는 또 다른 모종의 이슈로 LastPage가 다를 수 있으니 1이라는 값보다는 상수로 값의 특징을 명확하게 알려줘도 좋을 것 같아요

2024-11-21 02:47 UTC, kimeodml commented on src/components/Pagination/index.tsx
> +          disabled={currentPage + 1 === 1}
LAST_PAGE는 유동적이여서 일단 FIRST_PAGE만 반영했습니다!

2024-11-21 02:48 UTC, kimeodml commented on src/components/Pagination/index.tsx
> +  const { totalPage, currentPage } = pageInfo;
searchParams으로 받아온 값으로 currentPage가 대체되었습니다!

2024-11-21 02:51 UTC, kimeodml commented on src/components/Pagination/index.tsx
> +      </div>
동일한 로직이라 함수를 만드는 것을 불필요하다는 생각이 들어서 주석을 추가하였습니다!

2024-11-21 05:05 UTC, haejinyun approved these changes
수고하셨습니다!

2024-11-21 07:14 UTC, merged